poprawiono testy, dodano asercje zamiast zwykłych sprawdzeń.

diff --git a/src/Make_all_tests b/src/Make_all_tests
--- a/src/Make_all_tests
+++ b/src/Make_all_tests
@@ -2,22 +2,30 @@
 
 cd tests/
 rm -f test_*
+echo "Compiling tests:"
+g++ -w -g IO_file_test.cpp -o test_IO
+g++ -w -g varsizes_test.cpp -o test_varsize64
+g++ -m32 -w -g varsizes_test.cpp -o test_varsize32
+
+echo "Performing tests:"
 
 echo "IO test"
-g++ -w -g IO_file_test.cpp -o test_IO
 ./test_IO
 if [ $? = 0 ]; then
-    echo "Passed"
+    echo "* Passed"
 else
-    echo "Failed!"
+    echo "* Failed!"
 fi
-
-echo "variable size test"
-gcc -w -g varsizes_test.c -o test_varsize64
-gcc -m32 -w -g varsizes_test.c -o test_varsize32
-./test_varsize32 > ./test_varsize_output32
-./test_varsize64 > ./test_varsize_output64
-result_varsize=`diff -y ./test_varsize_output32 ./test_varsize_output64`
-echo $result_varsize
-echo "Passed"
-
+echo "Variable size tests"
+./test_varsize32
+if [ $? = 0 ]; then
+    echo "* Passed"
+else
+    echo "* Failed!"
+fi
+./test_varsize64
+if [ $? = 0 ]; then
+    echo "* Passed"
+else
+    echo "* Failed!"
+fi
